name: Fullstack CI - Integration and E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: |
          cd Backend
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run Backend
        run: |
          cd Backend
          uvicorn main:app --host 0.0.0.0 --port 8000 & 
          sleep 5

      - name: Run Integration Tests and Generate Report
        run: |
          cd Backend
          pytest test_api.py --html=backend-report.html

      - name: Upload Backend Test Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-html-report
          path: Backend/backend-report.html

      - name: Install Frontend Dependencies
        run: |
          cd Frontend
          npm install

      - name: Install Playwright Dependencies
        run: |
          cd Frontend
          npx playwright install

      - name: Set Executable Permissions for Playwright
        run: |
          cd Frontend
          chmod +x ./node_modules/.bin/playwright

      - name: Start Frontend App
        run: |
          cd Frontend
          npm start & 
          sleep 10

      - name: Run Playwright E2E Tests with Video and Report
        run: |
          cd Frontend
          npx playwright test --reporter=html

      - name: Upload Frontend HTML Report with Videos
        uses: actions/upload-artifact@v4
        with:
          name: frontend-playwright-report
          path: Frontend/playwright-report
